Add accuracy check
Signed-off-by: Huy Do <huydhn@gmail.com>

diff --git a/.github/workflows/gpt-oss-benchmark.yml b/.github/workflows/gpt-oss-benchmark.yml
--- a/.github/workflows/gpt-oss-benchmark.yml
+++ b/.github/workflows/gpt-oss-benchmark.yml
@@ -26,7 +26,7 @@ jobs:
             model: openai/gpt-oss-120b
             docker-image: rocm/vllm-dev:open-mi300-08052025
           # gpt-oss-20b
-          - runner: linux.aws.h100.4
+          - runner: linux.aws.h100
             model: openai/gpt-oss-20b
             docker-image: 'public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:6d8d0a24c02bfd84d46b3016b865a44f048ae84b'
           - runner: linux.dgx.b200
@@ -150,10 +150,12 @@ jobs:
           # vLLM-related environment variables
           ENGINE_VERSION: v1
           SAVE_TO_PYTORCH_BENCHMARK_FORMAT: 1
+          MODEL: ${{ matrix.model }}
         run: |
           set -eux
 
           if [[ "${DEVICE_TYPE}" == *B200* ]]; then
+            # Just to unblock this change on B200
             aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
             aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
             aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
@@ -184,6 +186,7 @@ jobs:
 
           container_name=$(docker run \
             ${GPU_FLAG:-} \
+            -e MODEL \
             -e DEVICE_NAME \
             -e DEVICE_TYPE \
             -e HF_TOKEN \
@@ -205,16 +208,76 @@ jobs:
             -w /tmp/workspace \
             "${DOCKER_IMAGE}"
           )
+
+          # Run perf tests
           docker exec -t "${container_name}" bash -c "
-            cd vllm-benchmarks/vllm
+            pushd vllm-benchmarks/vllm
             cp vllm/benchmarks/lib/utils.py /app/vllm-os-mini/vllm/benchmarks/utils.py || true
             if [[ $DEVICE_NAME != 'rocm' ]]; then
+              pip install -U openai transformers
               pip install --pre vllm==0.10.1+gptoss \
                 --extra-index-url https://wheels.vllm.ai/gpt-oss/ \
                 --extra-index-url https://download.pytorch.org/whl/nightly/cu128
             fi
-            sleep 7200
+            pip freeze
             bash .buildkite/nightly-benchmarks/scripts/run-performance-benchmarks.sh
+            popd
+          "
+
+          # Run accuracy check
+          docker exec -t "${container_name}" bash -c "
+            local tp
+            if [[ $MODEL == 'openai/gpt-oss-120b' ]]; then
+              tp=4
+            elfi [[ $MODEL == 'openai/gpt-oss-20b' ]]; then
+              tp=1
+            fi
+
+            # Prepare the accuracy test
+            vllm serve $MODEL --tensor_parallel_size $tp &
+            server_pid=$!
+
+            wait_for_server() {
+              timeout 1200 bash -c '
+                until curl -X POST localhost:8000/v1/completions; do
+                  sleep 1
+                done' && return 0 || return 1
+            }
+
+            if wait_for_server; then
+              echo 'vLLM server is up and running'
+            else
+              echo 'vLLM failed to start within the timeout period'
+            fi
+
+            pushd vllm-benchmarks/gpt-oss
+            mkdir -p /tmp/gpqa_openai
+
+            # Low
+            OPENAI_API_KEY='' python3 -m gpt_oss.evals --base-url http://localhost:8000/v1 \
+              --model $MODEL \
+              --eval gpqa \
+              --reasoning-effort low \
+              --n-threads $(expr $(nproc) / 2)
+
+            # Mid
+            OPENAI_API_KEY='' python3 -m gpt_oss.evals --base-url http://localhost:8000/v1 \
+              --model $MODEL \
+              --eval gpqa \
+              --reasoning-effort medium \
+              --n-threads $(expr $(nproc) / 2)
+
+            # High
+            OPENAI_API_KEY='' python3 -m gpt_oss.evals --base-url http://localhost:8000/v1 \
+              --model $MODEL \
+              --eval gpqa \
+              --reasoning-effort high \
+              --n-threads $(expr $(nproc) / 2)
+
+            mv /tmp/gpqa_openai .
+            popd
+
+            kill -9 $server_pid
           "
 
       - name: Authenticate with AWS
@@ -256,3 +319,10 @@ jobs:
         with:
           name: benchmark-results--${{ env.SANITIZED_DEVICE_TYPE }}-${{ env.SANITIZED_MODEL }}
           path: vllm-benchmarks/vllm/benchmarks/results
+
+      # Keep a copy of the accuracy results on GitHub for reference
+      - uses: actions/upload-artifact@v4
+        with:
+          name: accuracy-results--${{ env.SANITIZED_DEVICE_TYPE }}-${{ env.SANITIZED_MODEL }}
+          path: |
+            vllm-benchmarks/gpt-oss/gpqa_openai
